import {afterAll,afterEach,beforeEach,expect,it,vi} from "vitest";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
const state=vi.hoisted(()=>({user:{id:"acct_origin",name:"QA",email:"qa-origin",role:"ADMIN",title:"管理员"}}));
vi.mock("next/cache",()=>({revalidatePath(){}}));
vi.mock("next/navigation",()=>({notFound(){throw Error("NOT_FOUND")}}));
vi.mock("@/lib/auth",()=>({requireUser:async()=>state.user}));
vi.mock("@/lib/llm",async original=>({...await original<object>(),llmEnabled:async()=>false}));
vi.mock("@/app/(app)/customers/[id]/RecordView",()=>({default:()=>null}));
import {defaultClient as db} from "@/lib/prisma";
import {忘掉限定} from "@/lib/team-scope";
import {resetDb} from "./reset";
import Detail from "@/app/(app)/customers/[id]/page";
import {convertLead} from "@/app/(app)/leads/actions";
import {TOOLS,type ToolContext} from "@/lib/agent/tools";
import {DEFAULT_BUSINESS} from "@/lib/business-config";
const dir=fs.mkdtempSync(path.join(os.tmpdir(),"crm-origin-"));
const ctx=():ToolContext=>({userId:state.user.id,userName:"QA",b:DEFAULT_BUSINESS,recordOffset:0,proposals:[]});
const detail=(id:string)=>Detail({params:Promise.resolve({id}),searchParams:Promise.resolve({})});
const ai=(id:string)=>TOOLS.find(t=>t.name==="get_customer")!.run({id},ctx());
beforeEach(async()=>{vi.stubEnv("DESKTOP_LOCAL","0");vi.stubEnv("MULTI_TENANT","0");忘掉限定();state.user.role="ADMIN";await resetDb();await db.user.create({data:{...state.user,password:"qa"}})});
afterEach(()=>{忘掉限定();vi.unstubAllEnvs()});
afterAll(async()=>{await db.$disconnect();fs.rmSync(dir,{recursive:true,force:true})});
it("真实转化后详情和AI给出同一线索ID/姓名/来源/转化时间，历史缺时间不编造",async()=>{
 const lead=await db.lead.create({data:{id:"original-lead",name:"海川询盘",phone:"13800001111",source:"展会",ownerId:state.user.id}});
 const result=await convertLead(lead.id);if(!result.ok)throw Error(result.error);
 const saved=await db.lead.findUniqueOrThrow({where:{id:lead.id}});
 const expected={id:lead.id,name:lead.name,source:"展会",convertedAt:saved.convertedAt!.toISOString()};
 expect((await detail(result.customerId)).props.sourceLead).toEqual(expected);
 expect((await ai(result.customerId)).data).toMatchObject({sourceLead:expected});
 await db.lead.update({where:{id:lead.id},data:{convertedAt:null}});
 expect((await detail(result.customerId)).props.sourceLead).toMatchObject({convertedAt:null});
 expect((await ai(result.customerId)).data).toMatchObject({sourceLead:{convertedAt:null}});
});
it("未关联或原线索已删除不虚构来源，既有推荐关系保持独立",async()=>{
 const customer=await db.customer.create({data:{name:"客户",phone:"",salesOwnerId:state.user.id}});
 expect((await detail(customer.id)).props.sourceLead).toBeNull();expect((await ai(customer.id)).data).toMatchObject({sourceLead:null});
 await db.lead.create({data:{id:"deleted-origin",name:"已删除线索",customerId:customer.id,ownerId:state.user.id}});await db.lead.delete({where:{id:"deleted-origin"}});
 expect((await detail(customer.id)).props.sourceLead).toBeNull();
});
it("真实业务员权限限定：可见转化客户可追溯，自己持有的线索也不能绕过不可见客户",async()=>{
 const other=await db.user.create({data:{name:"同事",email:"origin-other",password:"qa"}});
 const visible=await db.customer.create({data:{name:"可见客户",phone:"",salesOwnerId:state.user.id}});
 const hidden=await db.customer.create({data:{name:"不可见客户",phone:"",salesOwnerId:other.id}});
 await db.lead.createMany({data:[{id:"visible-origin",name:"授权来源",customerId:visible.id,ownerId:other.id},{id:"hidden-origin",name:"秘密来源",customerId:hidden.id,ownerId:state.user.id}]});
 await db.user.update({where:{id:state.user.id},data:{role:"SALES"}});state.user.role="SALES";
 fs.writeFileSync(path.join(dir,".cloud.json"),JSON.stringify({baseUrl:"http://fake",token:"dk_qa",accountId:"origin",name:"QA",contact:state.user.email,models:[],loggedAt:new Date().toISOString()}));
 fs.writeFileSync(path.join(dir,".team.json"),JSON.stringify({teamId:"origin-team",key:"k".repeat(43),joinSecret:"qa",device:"origin-device",pulled:0}));vi.stubEnv("DESKTOP_LOCAL","1");vi.stubEnv("CRM_DATA_DIR",dir);忘掉限定();
 expect((await detail(visible.id)).props.sourceLead).toMatchObject({id:"visible-origin"});expect((await ai(visible.id)).data).toMatchObject({sourceLead:{id:"visible-origin"}});
 await expect(detail(hidden.id)).rejects.toThrow("NOT_FOUND");const forbidden=await ai(hidden.id);expect(forbidden.data).toMatchObject({error:"客户不存在"});expect(JSON.stringify(forbidden)).not.toContain("秘密来源");
});
