import {test,expect} from "@playwright/test";
import {连库,清空业务数据} from "./mock-data";
test.describe.configure({mode:"serial"});
let users:{id:string;name:string;active:boolean}[]=[];let ownerId:string,otherId:string;
test.beforeAll(async()=>{const db=连库();try{await 清空业务数据(db);users=await db.user.findMany({select:{id:true,name:true,active:true}});const owner=await db.user.findUniqueOrThrow({where:{email:"zhangsan"}});ownerId=owner.id;otherId=users.find(u=>u.id!==ownerId)!.id;await db.user.updateMany({where:{id:{not:ownerId}},data:{active:false}});await db.customer.create({data:{id:"solo-c",name:"QA个人客户",phone:"13800001111",salesOwnerId:ownerId}});await db.followUp.create({data:{id:"solo-f",customerId:"solo-c",ownerId,type:"PHONE",content:"QA跟进正文",title:"QA跟进",status:"已完成",occurredAt:new Date()}});await db.opportunity.create({data:{id:"solo-o",name:"QA个人商机",customerId:"solo-c",ownerId,stage:"初步沟通",amount:100}});await db.task.createMany({data:[{id:"solo-t",title:"QA个人待办",customerId:"solo-c",ownerId},{id:"solo-d",title:"QA个人已完成",customerId:"solo-c",ownerId,done:true,doneAt:new Date()}]})}finally{await db.$disconnect()}});
test.afterAll(async()=>{const db=连库();try{await 清空业务数据(db);for(const u of users)await db.user.update({where:{id:u.id},data:{name:u.name,active:u.active}})}finally{await db.$disconnect()}});
test("生产构建单人详情/管道/计划隐藏重复姓名，同名历史成员仍完整显示",async({page})=>{
 const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));await page.goto("/login");await page.getByPlaceholder("用户名").fill("zhangsan");await page.getByPlaceholder("登录密码").fill("admin123");await page.getByRole("button",{name:/登\s*录/}).click();await page.waitForURL(/\/dashboard/);
 await page.goto("/customers/solo-c");await expect(page.getByRole("main").locator(".rec-head-sub")).not.toContainText(users.find(u=>u.id===ownerId)!.name);await expect(page.getByRole("main").locator("#fu-solo-f .rec-tl-meta")).not.toContainText(users.find(u=>u.id===ownerId)!.name);
 await page.goto("/opportunities/pipeline");await expect(page.getByRole("main").locator(".pipe-card")).toHaveCount(1);await expect(page.getByRole("main").locator(".pipe-card-o")).toHaveCount(0);
 await page.goto("/follow-ups/plans?scope=all");await expect(page.getByRole("main").getByText("QA个人待办",{exact:true})).toBeVisible();await expect(page.getByRole("main").locator(".plan-row .ant-avatar")).toHaveCount(0);await page.getByRole("main").getByText("已完成 1",{exact:true}).click();await expect(page.getByRole("main").getByText("QA个人已完成",{exact:true})).toBeVisible();await expect(page.getByRole("main").locator(".plan-row .ant-avatar")).toHaveCount(0);
 const db=连库();try{await db.user.update({where:{id:otherId},data:{name:users.find(u=>u.id===ownerId)!.name}});await db.followUp.update({where:{id:"solo-f"},data:{ownerId:otherId}});await db.opportunity.update({where:{id:"solo-o"},data:{ownerId:otherId}});await db.task.update({where:{id:"solo-d"},data:{ownerId:otherId}})}finally{await db.$disconnect()}
 await page.goto("/customers/solo-c");await expect(page.getByRole("main").locator("#fu-solo-f .rec-tl-meta")).toContainText(users.find(u=>u.id===ownerId)!.name);await page.goto("/opportunities/pipeline");await expect(page.getByRole("main").locator(".pipe-card-o")).toHaveCount(1);await page.goto("/follow-ups/plans?scope=all");await page.getByRole("main").getByText("已完成 1",{exact:true}).click();await expect(page.getByRole("main").locator(".plan-row .ant-avatar")).toHaveCount(1);expect(errors).toEqual([]);
});
test("实际线索表单写全角国家码并保留原始附注，刷新和国家码搜索结果一致",async({page})=>{
 await page.goto("/login");await page.getByPlaceholder("用户名").fill("zhangsan");await page.getByPlaceholder("登录密码").fill("admin123");await page.getByRole("button",{name:/登\s*录/}).click();await page.waitForURL(/\/dashboard/);await page.goto("/leads");await page.getByRole("main").getByRole("button",{name:/新建线索$/}).click();const modal=page.getByRole("dialog");await modal.getByLabel("线索名称",{exact:true}).fill("QA全角线索");await modal.getByLabel("联系电话",{exact:true}).fill("＋８６ １３８－００００－２２２２（微信同号）");await modal.getByRole("button",{name:/保\s*存/}).click();await expect(modal).toBeHidden();
 const db=连库();try{const row=await db.lead.findFirstOrThrow({where:{name:"QA全角线索"}});expect(row.phone).toBe("13800002222");expect(row.remark).toContain("微信同号")}finally{await db.$disconnect()}
 await page.goto("/leads?keyword="+encodeURIComponent("＋８６ １３８００００２２２２"));await expect(page.getByRole("main").locator("tbody tr[data-row-key]")).toHaveCount(1);await expect(page.getByRole("main")).toContainText("QA全角线索");await page.reload();await expect(page.getByRole("main")).toContainText("QA全角线索");
});
